[package]
name = "proxide"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.6", features = ["macros"] }
mimalloc = "0.1.48"
object_store = { version = "0.12.4", features = ["aws"] }
reqwest = { version = "0.12.24", features = ["json", "stream"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "mysql", "chrono"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = [
  "signal",
  "rt-multi-thread",
  "macros",
  "time",
  "io-util",
  "sync",
] }
tower-http = { version = "0.6.6", features = [
  "timeout",
  "trace",
  "cors",
  "compression-full",
  "set-header",
] }

tracing = "0.1.41"
tracing-subscriber = "0.3.20"
utoipa = { version = "5.4.0", features = ["chrono"] }
utoipa-axum = "0.2.0"
utoipa-gen = "5.4.0"
utoipa-scalar = { version = "0.3.0", features = ["axum"] }
clap = { version = "4.5.51", features = ["derive"] }
fastrace = { version = "0.7.14", features = ["enable"] }
fastrace-tracing = "0.1.1"
toml = "0.9.8"
anyhow = "1.0.100"
log = "0.4.28"
logforth = { version = "0.29.1", features = ["starter-log"] }
async-trait = "0.1"
parking_lot = "0.12"
futures = "0.3"
percent-encoding = "2.3.2"
wiremock = "0.6.5"
semver = { version = "1.0", features = ["serde"] }
url = "2.5"
bytes = "1.10"
tokio-stream = "0.1"

[lints.rust]
async_fn_in_trait = "allow"
