use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Proxide",
        version = "0.1.0",
        description = "NPM registry mirror API",
    ),
    paths(
        crate::handlers::home::ping,
        crate::handlers::registry::registry_root,
        crate::handlers::registry::get_package_inner,
        crate::handlers::registry::get_package_version_inner,
        crate::handlers::tarball::download_tarball_inner,
        crate::handlers::publish::publish_package_inner,
        crate::handlers::auth::login,
        crate::handlers::web_login::init_login,
        crate::handlers::web_login::poll_done,
        crate::handlers::sync::trigger_sync,
        crate::handlers::search::search_packages,
        crate::handlers::fast_meta::resolve_version,
        crate::handlers::fast_meta::get_versions,
        crate::handlers::fast_meta::get_full,
        crate::handlers::downloads::downloads_point,
        crate::handlers::downloads::downloads_range,
        crate::handlers::sso::cas::cas_callback,
        crate::handlers::cdn::serve_file,
        crate::handlers::data_api::version_files,
    ),
    components(schemas(
        crate::handlers::home::Ping,
        crate::error::ApiErrorDetail,
        crate::npm::types::RegistryInfo,
        crate::npm::types::SyncResponse,
        crate::npm::types::FastMetaResolved,
        crate::npm::types::FastMetaVersions,
        crate::npm::types::FastMetaFull,
        crate::npm::types::VersionMeta,
        crate::npm::types::PublishPayload,
        crate::npm::types::PublishVersion,
        crate::npm::types::PublishDist,
        crate::npm::types::PublishAttachment,
        crate::npm::types::PublishResponse,
        crate::npm::types::LoginPayload,
        crate::npm::types::LoginResponse,
        crate::handlers::web_login::WebLoginResponse,
        crate::handlers::web_login::LoginRequestBody,
        crate::handlers::search::SearchResponse,
        crate::search::SearchDocument,
        crate::handlers::downloads::DownloadsPoint,
        crate::handlers::downloads::DownloadsRange,
        crate::handlers::downloads::DayDownloads,
    )),
    tags(
        (name = "registry", description = "NPM-compatible package manifest endpoints"),
        (name = "tarball", description = "Tarball download"),
        (name = "publish", description = "Package publishing"),
        (name = "auth", description = "Authentication (legacy login, CAS web login)"),
        (name = "sync", description = "On-demand package sync trigger"),
        (name = "search", description = "Package search (Meilisearch)"),
        (name = "fast-meta", description = "fast-npm-meta endpoints"),
        (name = "downloads", description = "Download count API"),
        (name = "cdn", description = "jsdelivr-compatible CDN file serving"),
    ),
)]
pub struct ApiDoc;
